---
- name: Leer report_*.html (sin dev) y enviar resumen a Teams
  hosts: windows
  gather_facts: false
  collections:
    - ansible.windows

  vars:
    reports_dir: 'C:\Reportes\Soatest'   # <-- AJUSTAR
    teams_webhook_url: 'https://webhook.site/25f54011-16bb-4cd9-a650-98f5253a74a2'               # <-- AJUSTAR (Incoming Webhook URL)

  tasks:
    - name: Encontrar el HTML del día que NO es dev/dev1
      ansible.windows.win_shell: |
        $dir = "{{ reports_dir }}"
        $today = (Get-Date).Date

        $html = Get-ChildItem -Path $dir -Filter "report_*.htm*" -File |
          Where-Object {
            $_.LastWriteTime.Date -eq $today -and
            $_.Name -notmatch 'dev' -and
            $_.Name -notmatch 'dev1\.html$'
          } |
          Sort-Object LastWriteTime -Descending |
          Select-Object -First 1

        if (-not $html) { throw "No encontré report_*.html válido de hoy en $dir" }

        @{ html_path = $html.FullName; html_name = $html.Name } | ConvertTo-Json
      register: found_html

    - name: Extraer métricas desde el HTML (Functional + Coverage)
      ansible.windows.win_shell: |
        $p = "{{ (found_html.stdout | from_json).html_path }}"
        $s = Get-Content -Path $p -Raw

        # 1) Functional: "Failed and Incomplete: 4/141"
        $m1 = [regex]::Match($s, 'Failed and Incomplete:\s*(\d+)\s*/\s*(\d+)', 'IgnoreCase')
        if (-not $m1.Success) { throw "No encontré 'Failed and Incomplete: X/Y' en $p" }
        $fail = [int]$m1.Groups[1].Value
        $total = [int]$m1.Groups[2].Value
        $pass = $total - $fail
        $successPct = [math]::Round(($pass*100.0)/$total, 1)

        # 2) API Coverage: buscar "(NN%)" cerca del anchor apicov (robusto)
        $m2 = [regex]::Match($s, '(?s)name="apicov".{0,8000}?\((\d+)%\)', 'IgnoreCase')
        if ($m2.Success) { $apiCoverage = [int]$m2.Groups[1].Value } else { $apiCoverage = $null }

        [PSCustomObject]@{
          fail = $fail
          pass = $pass
          total = $total
          success_pct = $successPct
          api_coverage_pct = $apiCoverage
        } | ConvertTo-Json -Depth 3
      register: metrics

  
    - name: Preparar variables (html + métricas)
      ansible.builtin.set_fact:
        html: "{{ found_html.stdout | from_json }}"
        m: "{{ metrics.stdout | from_json }}"

    - name: Preparar payload Teams (texto)
      ansible.builtin.set_fact:
        teams_payload:
          "@type": "MessageCard"
          "@context": "https://schema.org/extensions"
          summary: "SOAtest Daily Report"
          themeColor: "0076D7"
          title: "SOAtest - Reporte diario"
          text: >-
            **Archivo:** {{ html.html_name }}<br/>
            **Functional Tests:** {{ m.pass }}/{{ m.total }} OK, {{ m.fail }}/{{ m.total }} Fail/Incomplete ({{ m.success_pct }}%)<br/>
            **API Coverage:** {{ (m.api_coverage_pct is not none) | ternary((m.api_coverage_pct|string) ~ '%','(no encontrado en HTML)') }}
            
    - name: DEBUG - mostrar payload final
      ansible.builtin.debug:
        var: teams_payload        

    - name: Enviar a Teams por webhook
      ansible.builtin.uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        body_format: json
        body: "{{ teams_payload }}"
        status_code: [200]
      delegate_to: localhost
      when: teams_webhook_url | length > 0
